puts "hello world"
puts "hello again"
puts "I like typing this"
puts "This is fun."
puts "I like Drawing"
puts "i like painting"
puts "I \"said\" do not touch this"
puts "I'd must rather you 'not'"
# puts "what did it do"
